default: &default
  database:
    Type: mysql
    User: root
    Password: rootpwd
    Host: 127.0.0.1
    Name: karlmalone
    TablePrefix:

  redis:
    Host: 127.0.0.1:6379
    Password:
    MaxIdle: 30
    MaxActive: 30
    IdleTimeout: 200

  logger:
    Dir: ./log

  server:
    Port: :5288

dev:
  <<: *default

test:
  <<: *default

prod:
  <<: *default
