definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: skipmaple@gmail.com
    name: Drew Lee
  license:
    name: MIT License
    url: https://github.com/UncleMaple/Malone/blob/master/LICENSE.md
  title: Malone API
  version: 1.0-Beta
paths:
  /v0/auth/member_app_info:
    get:
      description: Get token by member_id
      parameters:
      - description: Member ID
        in: header
        name: member_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Member app info
      tags:
      - auth
  /v0/auth/parse_token:
    get:
      description: Parse token to member_id
      parameters:
      - description: Token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Parse token
      tags:
      - auth
  /v0/auth/token:
    get:
      description: Get a token by member_id in headers
      parameters:
      - description: Basic [base64-MemberID]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get token
      tags:
      - auth
  /v0/members/login:
    post:
      consumes:
      - multipart/form-data
      description: Member login
      parameters:
      - description: PhoneNum or Email
        in: formData
        name: account
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Login
      tags:
      - member
  /v0/members/register:
    post:
      consumes:
      - multipart/form-data
      description: Member register
      parameters:
      - description: PhoneNum
        in: formData
        name: phone_num
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Nickname
        in: formData
        name: nickname
        required: true
        type: string
      - default: U
        description: Gender(Male Female Unknown)
        enum:
        - M
        - F
        - U
        in: formData
        name: gender
        required: true
        type: string
      - description: Avatar
        in: formData
        name: avatar
        type: string
      - description: Memo
        in: formData
        name: memo
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Register
      tags:
      - member
  /v1/contacts/add_friend:
    post:
      consumes:
      - multipart/form-data
      description: member add friend
      parameters:
      - description: OwnerId
        in: formData
        name: owner_id
        required: true
        type: string
      - description: DstId
        in: formData
        name: dst_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: add_friend
      tags:
      - contacts
  /v1/contacts/create_group:
    post:
      consumes:
      - multipart/form-data
      description: create group
      parameters:
      - description: OwnerId
        in: formData
        name: owner_id
        required: true
        type: string
      - description: GroupName
        in: formData
        name: name
        required: true
        type: string
      - description: icon
        in: formData
        name: icon
        type: string
      - description: memo
        in: formData
        name: memo
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: create_group
      tags:
      - contacts
  /v1/contacts/find_group_members:
    get:
      description: Find group members by group_id
      parameters:
      - description: GroupId
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Find group members
      tags:
      - contacts
  /v1/contacts/join_group:
    post:
      consumes:
      - multipart/form-data
      description: join group
      parameters:
      - description: OwnerId
        in: formData
        name: owner_id
        required: true
        type: string
      - description: GroupName
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: join_group
      tags:
      - contacts
  /v1/contacts/load_friend:
    get:
      description: load friend list
      parameters:
      - description: OwnerId
        in: query
        name: owner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: load_friend
      tags:
      - contacts
  /v1/contacts/load_group:
    get:
      description: load group list
      parameters:
      - description: OwnerId
        in: query
        name: owner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: load_group
      tags:
      - contacts
  /v1/members/find:
    get:
      description: Find member by member_id
      parameters:
      - description: MemberId
        in: query
        name: member_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Find member by member_id
      tags:
      - member
  /v1/members/logout:
    get:
      description: Logout member by member_id
      parameters:
      - description: MemberId
        in: query
        name: member_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Logout member by member_id
      tags:
      - member
swagger: "2.0"
